### ISSUE TITLE
googleapis.com font urls need to be requested with https 

### ISSUE THREAD

**Issue by sargsyan** [volny/creative-theme-jekyll#16]
Easy to fix yet important issue

Because googleapis.com is requested with http protocol rather than https "Insecure content blocked" security error is reported by google chrome. This message alone looks pretty scary.

<img width="320" alt="screen shot 2018-11-16 at 10 54 05 pm" src="https://user-images.githubusercontent.com/10484593/48649550-404e5400-e9f3-11e8-8a1b-fb85281fa1dc.png">

To fix the issue https needs to be used in following links links in head.html

<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

**Comment by volny** [comment]
fixed by 1ee7ef6aeb67d1227dbd24bc28dd97eb6eee48e2
